[staging]
vm-ai-job-2 ansible_aws_ssm_instance_id=i-0d845b5bbf628b67a

[staging:vars]
ansible_connection=community.aws.aws_ssm
ansible_python_interpreter=/usr/bin/python3
ansible_aws_ssm_bucket_name=100xteamai-ansible-ci
ansible_aws_ssm_s3_addressing_style=virtual
ansible_aws_ssm_region=us-east-1
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
